### ISSUE TITLE
WindBot won't join the room

### ISSUE THREAD

**Issue by mattiacolucci** [IceYGO/windbot#172]
Hi, I downloaded your project to make new ai and use them on Edopro by Project ignis. I create a new executor and add deck to the "deck" folder; then I add card db on debug folder; open solution on VS and set as parameter "Deck=Zarc" (I am creating a Zarc bot). I named "ZarcExecutor" the executor and "AI_Zarc" the deck. After that I start debug and Windbot start but not join the room, preaviously created on LAN. How can I let the bot join the room? What I have done wrong? 

Here is the code of the Executor:
`using YGOSharp.OCGWrapper.Enums;
using System.Collections.Generic;
using WindBot;
using WindBot.Game;
using WindBot.Game.AI;
using System.Linq;

namespace WindBot.Game.AI.Decks
{
    [Deck("Zarc", "AI_Zarc")]

    public class ZarcExecutor : DefaultExecutor
    {

        public ZarcExecutor(GameAI ai, Duel duel)
        : base(ai, duel)
        {

        }
    }
}
`

It's the default code given on the wiki

**Comment by mercury233** [comment]
You should use https://github.com/ProjectIgnis/windbot for EDOPro.

I guess it is because EDOPro and YGOPro don't have same version:
https://github.com/IceYGO/windbot/blob/master/WindBotInfo.cs#L27
https://github.com/ProjectIgnis/windbot/blob/master/WindBotInfo.cs#L54
https://github.com/Fluorohydride/ygopro/blob/master/gframe/game.cpp#L13
